### ISSUE TITLE
Safari cannot install TweetDeck Enhancer

### ISSUE THREAD

**Issue by nintyapple** [dangeredwolf/TweetDeck-Enhancer#12]
I have reported this to you on Twitter, but I assume that it has gotten lost in all your mentions. Safari throws me this error when I try installing: 
![screen shot 2015-01-05 at 8 22 51 pm](https://cloud.githubusercontent.com/assets/5097035/5622956/4f13cfde-9519-11e4-9f54-13d67288cdbd.png)

Steps to reproduce on Safari 8.0.3: 
1. Download Safari extension on https://ryandolan123.com/TweetDeckEnhancer
2. Click the downloaded extension in Finder.
3. Receive this pop-up and choose "Install": 
![screen shot 2015-01-05 at 8 29 19 pm](https://cloud.githubusercontent.com/assets/5097035/5622976/8b51fdfe-9519-11e4-9b8b-9d5f9d739922.png)
4. You will receive this error.

Since I am not a Chrome user, I hope that you can fix this soon! Enjoy the rest of your day/winter break (if there is any left :P)! ^.^

**Comment by Apph3x** [comment]
Why are you using the one linked ? Try downloading the one in this repo (zipped)

**Comment by nintyapple** [comment]
@Apph3x I have tried using the one on the repo, but I figure the one on his site is considered the "official build" (even though there might not even be a difference). I've even tried loading the .safariextension folder into the Safari's Extension Builder (Safari -> Develop -> Show Extension Builder or if Develop isn't there, then Safari -> Preferences -> Advanced and select the Show Develop menu in menu bar option) and building the extension there/installing it there.

**Comment by Apph3x** [comment]
There is a difference the repo one is more recent, do u have a Safari dev cert installed, you need it to build them

**Comment by nintyapple** [comment]
@Apph3x Nope, I used my magical fairy powers to build it. Of course I have a Safari certificate, how else would I have built it? Did *you* ever get TweetDeck Enhancer to install in Safari?

**Comment by Apph3x** [comment]
Yeah actually I did

-----Original Message-----

**Comment by nintyapple** [comment]
@Apph3x Forgive me for being skeptical, but may I see a screenshot?

**Comment by Apph3x** [comment]
Yeah, sure, although this is the old, old 4.0 build

-----Original Message-----

**Comment by tbraun1551** [comment]
@Apph3x @nintyapple I have done the exact same thing as you and I have also been unable to install the extension on Safari 8.0.3. I have also tried the one from the website and signing the one here with a certificate but that has produced the exact same error.

**Comment by Apph3x** [comment]
yep @tbraun1551

**Comment by tbraun1551** [comment]
@Apph3x Is there a fix for it

**Comment by Apph3x** [comment]
IDK @tbraun1551

**Comment by arcticsn0w** [comment]
Anybody tried this on 8.0.4 yet?
