### ISSUE TITLE
Add ability to merge 2 lists

### ISSUE THREAD

**Issue by kurtextrem** [dangeredwolf/TweetDeck-Enhancer#19]
I'm not sure how complicated that would be, but is it possible to add the ability to merge two lists? What I mean with that:
I have list A + its tweets in a column
I have list B + its tweets in a column
When I "merge" them, a column is added which displays both in a single one.

**Comment by dangeredwolf** [comment]
I don't know how possible this could be. That'd be really confusing to make and I don't have the ability to (yet) I don't think.
