### ISSUE TITLE
Chrome: side bar profile image doesn't load due HTTP 429 response code (Too Many Requests)

### ISSUE THREAD

**Issue by miguelfito** [dangeredwolf/TweetDeck-Enhancer#23]
Hi,

**TweetDeck-Enhancer** side bar does not load the profile image and data due an error fetching data,  always asks for waiting or refreshing the page:

![captura de pantalla 2015-03-18 a las 23 43 32](https://cloud.githubusercontent.com/assets/879123/6721036/322bcd34-cdc9-11e4-8075-4b03d927f991.png)

Debugging it deeper, it seems to be an error caused because the extension is always getting **HTTP 429** response code (**Too Many Requests**):

![captura de pantalla 2015-03-18 a las 23 53 15](https://cloud.githubusercontent.com/assets/879123/6721118/0f526eca-cdca-11e4-865e-b8ebd7e22aca.png)

**Comment by dangeredwolf** [comment]
Too many requests is a Twitter API issue beyond my control, so I can't do much at all to fix that.
