### ISSUE TITLE
TDE for Mac Desktop opens Chrome Canary

### ISSUE THREAD

**Issue by arcticsn0w** [dangeredwolf/TweetDeck-Enhancer#24]
So I was playing with the TDE version for OS X desktop, and after one launch/close, it just opens Chrome Canary.

I never even installed Chrome Canary.

What happened?

EDIT: It's sort of on-off now; sometimes it does, sometimes it doesn't.

Also, Chrome Canary opens when clicking on a link rather than the install of Chrome Stable I already have.

May I recommend using Chromium Embedded Framework rather than a hacky script? :P

**Comment by arcticsn0w** [comment]
So it's sort of sporradic now; sometimes it does, sometimes it doesn't.

**Comment by arcticsn0w** [comment]
Crap, I closed the issue. Oops.

**Comment by dangeredwolf** [comment]
Yeah that's probably a better way to move, but in the meantime I'll have to close this. I will definitely consider it though.

**Comment by arcticsn0w** [comment]
No, I mean when opening TDE for Mac via the Dock it spawns another icon in the Dock.

When closing TDE (not quitting it) and then opening it again, it opens full-fledged Chrome Canary. The full browser. With tabs.

**Comment by dangeredwolf** [comment]
I know.

**Comment by arcticsn0w** [comment]
Okay.
