### ISSUE TITLE
A new console windows opens every time TweetDeck is launched.

### ISSUE THREAD

**Issue by antolovich** [dangeredwolf/TweetDeck-Enhancer#35]
After installing TDE on OSX through the installer, every time TweetDeck is launched a new console window opens as well.

**Comment by dangeredwolf** [comment]
Cannot reproduce

**Comment by antolovich** [comment]
When I get free time tomorrow I will reinstall and attempt to reproduce.

**Comment by yukimono** [comment]
Basic checklist;

1. What browser + version were you using? 
2. Are debug/developer options enabled? 
3. What OSX version are you running? 
4. What other extensions do you have that can run on tweetdeck.twitter.com?
